project:
  type: site
  output-dir: docs

website:
  title: "zg.dev"
  navbar:
    type: dark
    background: secondary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    toc: true
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css

editor: visual

