project:
  type: site
  output-dir: docs

website:
  title: "zg.dev"
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "A Quarto Doc"
        contents:
          - index.qmd
          - obs.qmd
          - py.qmd
          - js.qmd
          - rmd.qmd
          - shiny.qmd
  navbar:
    type: light
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
format:
  html:
    toc: true
    theme:
      light: [flatly, theme.scss]
      dark: [flatly, theme-dark.scss]
    highlight: tango
    code-copy: true
    code-overflow: wrap
    css: styles.css

editor: visual

