---
title: "product-dev"
format: html
server: shiny
---

```{r}
sliderInput("bins", "Number of bins:", 
            min = 1, max = 50, value = 30)
plotOutput("distPlot")
```

```{r}
#| context: server
output$distPlot <- renderPlot({
  x <- faithful[, 2]  # Old Faithful Geyser data
  bins <- seq(min(x), max(x), length.out = input$bins + 1)
  hist(x, breaks = bins, col = 'darkgray', border = 'white')
})
```
```{r}
shiny::HTML('
  <div class="accordion" id="toc-content-container">
<h3>Contents</h3>
<div class="card">
<div class="card-header" id="headingOne">
<h2 class="mb-0">
<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
<!-- <span>&#8544;&nbsp;</span>  -->
Ⅰ Product Design
</button>
</h2>
</div>

<div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#toc-content-container" style="">
<div class="card-body">
<ul>
<li>1. Building vs. Scaling</li>
<li>2. Solving the Right Problem</li>
<li>3. Hypothesis Testing</li>
<li>4. Minimum Lovable Products</li>
</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingTwo">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
<!-- <span>&#8545;&nbsp;</span>  -->
Ⅱ Economics
</button>
</h2>
</div>
<div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#toc-content-container" style="">
<div class="card-body">
<ul>
<li>5. Businses Models</li>
<li>6. Market Entry</li>
<li>7. Moats</li>
<li>8. Unit Economics</li>
<li>9. Customer Economics</li>
<li>10. Segmentation</li>
<li>11. Market Failures</li>

</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingThree">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
<!-- <span>&#8546;&nbsp;</span> -->
Ⅲ Psychology
</button>
</h2>
</div>
<div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#toc-content-container">
<div class="card-body">
<ul>
<li>12. Pricing Psycology</li>
<li>13. Motivation</li>
<li>14. Getting the Click</li>
<li>15. Stickiness</li>
</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingFour">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
<!-- <span>&#8547;&nbsp;</span>  -->
Ⅳ User Experience
</button>
</h2>
</div>
<div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#toc-content-container">
<div class="card-body">
<ul>
<li>16. Cognition</li>
<li>17. UX Principles</li>
<li>18. Usability</li>
<li>19. Customer vs. Business</li>
</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingFive">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
<!-- <span>&#8548;&nbsp;</span> -->
Ⅴ Data Science
</button>
</h2>
</div>
<div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#toc-content-container">
<div class="card-body">
<ul>
<li>20. Distributions of Data</li>
<li>21. Experiments</li>
<li>22. Metrics</li>
<li>23. Metric Models</li>
<li>24. Storytelling with Data</li>
</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingSix">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
<!-- <span>&#8549;&nbsp;</span> -->
Ⅵ Law and Policy
</button>
</h2>
</div>
<div id="collapseSix" class="collapse" aria-labelledby="headingSix" data-parent="#toc-content-container">
<div class="card-body">
<ul>
<li>25. Antitrust</li>
<li>26. Intellectual Property</li>
<li>27. Platform Liability</li>
<li>28. Privacy</li>
<li>29. Employment in the Gig Economy</li>
<li>30. Accessibility</li>
</ul>
</div>
</div>
</div>
<div class="card">
<div class="card-header" id="headingSeven">
<h2 class="mb-0">
<button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseSeven" aria-expanded="false" aria-controls="collapseSeven">
<!-- <span>&#8550;&nbsp;</span>  -->
Ⅶ Marketing &amp; Growth
</button>
</h2>
</div>
<div id="collapseSeven" class="collapse" aria-labelledby="headingSeven" data-parent="#toc-content-container">
<div class="card-body">
<ul>
<li>31. Branding</li>
<li>32. What Are You Hunting?</li>
<li>33. Advertising</li>
<li>34. Growth Hacking</li>
<li>35. Persuasion</li>
</ul>
</div>
</div>
</div>
  
')
```
